version: "3"
services:
  web:
    build: .
    # command: sh /code/run.sh
    command: gunicorn api:__hug_wsgi__ --bind 0.0.0.0:80 --reload
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: dev.env
    ports:
      - '8002:80'